/* SHOES */
DROP TABLE IF EXISTS `shoes`;
CREATE TABLE shoes (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    us_size FLOAT NOT NULL,
    cm_size DECIMAL(10,2),
    uk_size DECIMAL(10,2),
    eu_size DECIMAL(10,2),
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;

/* SIZES */
DROP TABLE IF EXISTS `sizes`;
CREATE TABLE sizes (
    id INT(11) NOT NULL AUTO_INCREMENT,
    size FLOAT NOT NULL UNIQUE,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
